Fix local wheel install
tskit-dev/tskit pull request #2030
Opened 2021-12-07 16:29 UTC by benjeffery

Spotted by @grahamgower

2021-12-07 17:35 UTC, jeromekelleher requested changes
Doesn't look right to me

2021-12-07 17:35 UTC, jeromekelleher commented on .github/workflows/wheels.yml
> +          pip install pip install dist/tskit-*.whl
Looks like an extra "pip install"?

2021-12-08 11:13 UTC, benjeffery commented
Wow, I even read through the diff. Send help! Fixed.

2021-12-08 11:50 UTC, jeromekelleher approved these changes
LGTM

2021-12-08 12:43 UTC, merged